1. Instalação das bibliotecas

In [5]:
!pip install requests beautifulsoup4 pandas

Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (2.32.3)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (4.13.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests) (2025.7.14)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4) (4.14.1)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

2. Importação das bibliotecas

In [6]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

3. Definição da URL e headers

In [7]:
url = "https://pt.wikipedia.org/wiki/Lista_das_maiores_empresas_do_mundo_por_receita"
headers = { 'User-Agent': 'Mozilla/5.0 ...' }

4. Download do conteúdo HTML

In [8]:
response = requests.get(url, headers=headers)
response.raise_for_status()

5. Parsing com BeautifulSoup

In [10]:
soup = BeautifulSoup(response.content, 'html.parser')

6. Buscar a tabela desejada na página

In [11]:
table = soup.find('table', {'class': 'wikitable'})
if table is None:
    table = soup.find('table', {'class': 'wikitable sortable'})

7. Extrair tabela para DataFrame com pandas

In [12]:
dfs = pd.read_html(str(table))
df_empresas = dfs[0]

/tmp/ipython-input-4174359609.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  dfs = pd.read_html(str(table))

8. Visualização da tabela e estrutura

In [13]:
print("Tabela extraída com sucesso:")
display(df_empresas.head())
display(df_empresas.info())

Tabela extraída com sucesso:

,Classificação,Nome,Indústria,Receita (bilhões de USD),Crescimento da receita,Empregados,País,Sede,CEO,Ref.(s)
0,1,Walmart,Varejo,$482,"0,7%",2.300.000,NaN,Bentonville (Arkansas),Doug McMillon,[1]
1,2,State Grid,Eletrônicos,$330,"2,9%",927.839,NaN,Pequim,Shu Yinbiao,[2]
2,3,China National Petroleum,Petróleo e gás,$299,"30,2%",1.589.508,NaN,Pequim,Wang Yilin,[3]
3,4,Sinopec,Petróleo e gás,$294,"34,1%",810.538,NaN,Pequim,Wang Yupu,[4]
4,5,Royal Dutch Shell,Petróleo e gás,$272,"36,9%",90.000,NaN,Haia,Ben van Beurden,[5]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Classificação             46 non-null     int64
 1   Nome                      46 non-null     object
 2   Indústria                 46 non-null     object
 3   Receita (bilhões de USD)  46 non-null     object
 4   Crescimento da receita    46 non-null     object
 5   Empregados                46 non-null     object
 6   País                      0 non-null      float64
 7   Sede                      46 non-null     object
 8   CEO                       46 non-null     object
 9   Ref.(s)                   46 non-null     object
dtypes: float64(1), int64(1), object(8)
memory usage: 3.7+ KB

None

9. Extração da coluna 'países'

In [14]:
paises = []

In [15]:
rows = table.find_all('tr')

In [16]:
for row in rows[1:]:
    cells = row.find_all('td')

    # Verifica se a linha tem células suficientes para pegar o país (normalmente 7 colunas, índice 6)
    if len(cells) > 6:
        pais_cell = cells[6]  # Coluna 7 (índice 6) contém o país
        pais = pais_cell.get_text(strip=True)  # Pega o texto limpo da célula
        paises.append(pais)
    else:
        paises.append(None)  # Caso a linha não tenha dados suficientes, adiciona None

In [17]:
if len(paises) == len(df_empresas):
    df_empresas['País Extraído'] = paises
    print("Coluna 'País Extraído' adicionada ao DataFrame.")
else:
    print("Erro: número de países extraídos não corresponde ao número de linhas do DataFrame.")

Coluna 'País Extraído' adicionada ao DataFrame.

In [19]:
print("Valores únicos e contagem na coluna 'Sede':")
display(df_empresas['Sede'].value_counts())
sede_para_pais = {
    'Pequim': 'China',
    'Bentonville (Arkansas)': 'United States',
    'Haia': 'Países Baixos',
    'Irving (Texas)': 'United States',
    'Wolfsburg': 'Germany',
    'Toyota (Aichi)': 'Japan',
    'Cupertino': 'United States',
    'Londres': 'United Kingdom',
    'Omaha (Nebraska)': 'United States',
    'San Francisco': 'United States',
    'Suwon': 'South Korea',
    'Baar': 'Switzerland',
    'Courbevoie': 'France',
    'Houston': 'United States',
    'Tóquio': 'Japan',
    'Stuttgart': 'Germany',
    'Detroit': 'United States',
    'Boston': 'United States',
    'Turim': 'Italy',
    'Munique': 'Germany',
    'Dearborn (Michigan)': 'United States',
    'Rio de Janeiro': 'Brazil',
    'Moscou': 'Russia',
    'Tokyo': 'Japan',
    'Woonsocket (Rhode Island)': 'United States',
    'San Ramon (Califórnia)': 'United States',
    'Düsseldorf': 'Germany',
    'Taiwan': 'Taiwan',
    'Roma': 'Italy',
    'Dallas': 'United States',
    'San Antonio, Texas': 'United States',
    'Minnetonka (Minnesota)': 'United States',
    'Caracas': 'Venezuela',
    'Lucerna': 'Switzerland',
    'Nova York': 'United States',
    'Wayzata (Minnesota)': 'United States',
    'Chesterbrook (Pensilvânia)': 'United States',
    'Wichita (Kansas)': 'United States',
    'Issaquah': 'United States',
    'Palo Alto': 'United States',
    'Mumbai': 'India'
}

Valores únicos e contagem na coluna 'Sede':

Sede
Pequim                        6
Bentonville (Arkansas)        1
Haia                          1
Irving (Texas)                1
Wolfsburg                     1
Toyota (Aichi)                1
Cupertino                     1
Londres                       1
Omaha (Nebraska)              1
San Francisco                 1
Suwon                         1
Baar                          1
Courbevoie                    1
Houston                       1
Tóquio                        1
Stuttgart                     1
Detroit                       1
Boston                        1
Turim                         1
Munique                       1
Dearborn (Michigan)           1
Rio de Janeiro                1
Moscou                        1
Tokyo                         1
Woonsocket (Rhode Island)     1
San Ramon (Califórnia)        1
Düsseldorf                    1
Taiwan                        1
Roma                          1
Dallas                        1
San Antonio, Texas            1
Minnetonka (Minnesota)        1
Caracas                       1
Lucerna                       1
Nova York                     1
Wayzata (Minnesota)           1
Chesterbrook (Pensilvânia)    1
Wichita (Kansas)              1
Issaquah                      1
Palo Alto                     1
Mumbai                        1
Name: count, dtype: int64

In [20]:
df_empresas['País Final'] = df_empresas['Sede'].map(sede_para_pais)
print("\nDataFrame com a nova coluna 'País Final':")
display(df_empresas.head())

DataFrame com a nova coluna 'País Final':

,Classificação,Nome,Indústria,Receita (bilhões de USD),Crescimento da receita,Empregados,País,Sede,CEO,Ref.(s),País Extraído,País Final
0,1,Walmart,Varejo,$482,"0,7%",2.300.000,NaN,Bentonville (Arkansas),Doug McMillon,[1],Bentonville (Arkansas),United States
1,2,State Grid,Eletrônicos,$330,"2,9%",927.839,NaN,Pequim,Shu Yinbiao,[2],Pequim,China
2,3,China National Petroleum,Petróleo e gás,$299,"30,2%",1.589.508,NaN,Pequim,Wang Yilin,[3],Pequim,China
3,4,Sinopec,Petróleo e gás,$294,"34,1%",810.538,NaN,Pequim,Wang Yupu,[4],Pequim,China
4,5,Royal Dutch Shell,Petróleo e gás,$272,"36,9%",90.000,NaN,Haia,Ben van Beurden,[5],Haia,Países Baixos

In [21]:
print("\nContagem de valores não nulos na coluna 'País Final':")
display(df_empresas['País Final'].count())

print("\nValores únicos na coluna 'País Final':")
display(df_empresas['País Final'].value_counts())

Contagem de valores não nulos na coluna 'País Final':

np.int64(46)

Valores únicos na coluna 'País Final':

País Final
United States     20
China              6
Germany            4
Japan              3
Switzerland        2
Italy              2
Países Baixos      1
South Korea        1
United Kingdom     1
France             1
Brazil             1
Russia             1
Taiwan             1
Venezuela          1
India              1
Name: count, dtype: int64

10. Importação da base da superstore para comparação

In [23]:
import pandas as pd
df_superstore = pd.read_csv('superstore.csv')
display(df_superstore.head())
display(df_superstore.info())

,category,city,country,customer_ID,customer_name,discount,market,unknown,order_date,order_id,...,sales,segment,ship_date,ship_mode,shipping_cost,state,sub_category,year,market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07 0:00:00,CA-2011-130813,...,19,Consumer,2011-01-09 0:00:00,Second Class,4.37,California,Paper,2011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21 0:00:00,CA-2011-148614,...,19,Consumer,2011-01-26 0:00:00,Standard Class,0.94,California,Paper,2011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 0:00:00,CA-2011-118962,...,21,Consumer,2011-08-09 0:00:00,Standard Class,1.81,California,Paper,2011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 0:00:00,CA-2011-118962,...,111,Consumer,2011-08-09 0:00:00,Standard Class,4.59,California,Paper,2011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,2011-09-29 0:00:00,CA-2011-146969,...,6,Consumer,2011-10-03 0:00:00,Standard Class,1.32,California,Paper,2011,North America,40

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   category        51290 non-null  object
 1   city            51290 non-null  object
 2   country         51290 non-null  object
 3   customer_ID     51290 non-null  object
 4   customer_name   51290 non-null  object
 5   discount        51290 non-null  float64
 6   market          51290 non-null  object
 7   unknown         51290 non-null  int64
 8   order_date      51290 non-null  object
 9   order_id        51290 non-null  object
 10  order_priority  51290 non-null  object
 11  product_id      51290 non-null  object
 12  product_name    51290 non-null  object
 13  profit          51290 non-null  float64
 14  quantity        51290 non-null  int64
 15  region          51290 non-null  object
 16  row_id          51290 non-null  int64
 17  sales           51290 non-null  int64
 18  segment         51290 non-null  object
 19  ship_date       51290 non-null  object
 20  ship_mode       51290 non-null  object
 21  shipping_cost   51290 non-null  float64
 22  state           51290 non-null  object
 23  sub_category    51290 non-null  object
 24  year            51290 non-null  int64
 25  market2         51290 non-null  object
 26  weeknum         51290 non-null  int64
dtypes: float64(3), int64(6), object(18)
memory usage: 10.6+ MB

None

11. Limpeza da base de concorrentes

In [25]:
# Remove caracteres e converte para float
df_empresas['Receita (bilhões de USD)'] = df_empresas['Receita (bilhões de USD)'].astype(str).str.replace('$','').str.replace(',', '.')
df_empresas['Receita (bilhões de USD)'] = pd.to_numeric(df_empresas['Receita (bilhões de USD)'])

df_empresas['Crescimento da receita'] = df_empresas['Crescimento da receita'].astype(str).str.replace('%','').str.replace(',', '.').str.replace('..', '.')
df_empresas['Crescimento da receita'] = pd.to_numeric(df_empresas['Crescimento da receita'])

df_empresas['Empregados'] = df_empresas['Empregados'].astype(str).str.replace('.', '')
df_empresas['Empregados'] = pd.to_numeric(df_empresas['Empregados'])

In [26]:
df_empresas = df_empresas.drop(columns=['País', 'País Extraído', 'Ref.(s)'])

12. Análise sobre os concorrentes

In [27]:
print("Unique values in 'Indústria' from df_empresas:")
display(df_empresas['Indústria'].value_counts())

print("\nUnique values in 'category' from df_superstore:")
display(df_superstore['category'].value_counts())

print("\nUnique values in 'sub_category' from df_superstore:")
display(df_superstore['sub_category'].value_counts())

Unique values in 'Indústria' from df_empresas:

Indústria
Petróleo e gás          13
Automotiva               6
Conglomerado             6
Eletrônicos              4
Varejo                   3
Serviços financeiros     3
Farmacêutica             2
Commodities              2
Telecomunicações         2
Transportes              1
Energia                  1
Plano de saúde           1
Construção               1
Comida processada        1
Name: count, dtype: int64

Unique values in 'category' from df_superstore:

category
Office Supplies    31273
Technology         10141
Furniture           9876
Name: count, dtype: int64

Unique values in 'sub_category' from df_superstore:

sub_category
Binders        6152
Storage        5059
Art            4883
Paper          3538
Chairs         3434
Phones         3357
Furnishings    3170
Accessories    3075
Labels         2606
Envelopes      2435
Supplies       2425
Fasteners      2420
Bookcases      2411
Copiers        2223
Appliances     1755
Machines       1486
Tables          861
Name: count, dtype: int64

In [28]:
potential_competitor_industries = ['Eletrônicos', 'Varejo']
df_competitors = df_empresas[df_empresas['Indústria'].isin(potential_competitor_industries)].copy()

print("\nPotential Competitors based on Industry:")
display(df_competitors)

Potential Competitors based on Industry:

,Classificação,Nome,Indústria,Receita (bilhões de USD),Crescimento da receita,Empregados,Sede,CEO,País Final
0,1,Walmart,Varejo,482.0,0.7,2300000,Bentonville (Arkansas),Doug McMillon,United States
1,2,State Grid,Eletrônicos,330.0,2.9,927839,Pequim,Shu Yinbiao,China
8,9,Apple,Eletrônicos,234.0,27.9,72494,Cupertino,Tim Cook,United States
27,31,CVS Health,Varejo,139.0,9.9,208000,Woonsocket (Rhode Island),Larry Merlo,United States
31,35,Foxconn,Eletrônicos,133.0,6.6,1290000,Taiwan,Terry Gou,Taiwan
43,47,Costco,Varejo,114.0,7.1,189000,Issaquah,W. Craig Jelinek,United States
44,48,Hewlett Packard Enterprise,Eletrônicos,111.0,0.8,302000,Palo Alto,Meg Whitman,United States

In [29]:
print("Distribution of companies in df_competitors by Industry:")
display(df_competitors['Indústria'].value_counts())

print("\nComparing df_competitors industries with df_superstore categories and sub-categories:")
print(f"Industries in df_competitors: {df_competitors['Indústria'].unique()}")
print(f"Categories in df_superstore: {df_superstore['category'].unique()}")
print(f"Sub-categories in df_superstore: {df_superstore['sub_category'].unique()}")

# Escolha setores relevantes
relevant_industries_for_superstore = ['Eletrônicos', 'Varejo']

top_competitors_in_relevant_industries = df_competitors[
    df_competitors['Indústria'].isin(relevant_industries_for_superstore)
].sort_values(by='Classificação').head(10)

print("\nTop 10 Potential Competitors in Industries relevant to Superstore:")
display(top_competitors_in_relevant_industries)

Distribution of companies in df_competitors by Industry:

Indústria
Eletrônicos    4
Varejo         3
Name: count, dtype: int64

Comparing df_competitors industries with df_superstore categories and sub-categories:
Industries in df_competitors: ['Varejo' 'Eletrônicos']
Categories in df_superstore: ['Office Supplies' 'Technology' 'Furniture']
Sub-categories in df_superstore: ['Paper' 'Art' 'Storage' 'Appliances' 'Supplies' 'Envelopes' 'Fasteners'
 'Labels' 'Binders' 'Accessories' 'Phones' 'Copiers' 'Machines' 'Tables'
 'Bookcases' 'Chairs' 'Furnishings']

Top 10 Potential Competitors in Industries relevant to Superstore:

,Classificação,Nome,Indústria,Receita (bilhões de USD),Crescimento da receita,Empregados,Sede,CEO,País Final
0,1,Walmart,Varejo,482.0,0.7,2300000,Bentonville (Arkansas),Doug McMillon,United States
1,2,State Grid,Eletrônicos,330.0,2.9,927839,Pequim,Shu Yinbiao,China
8,9,Apple,Eletrônicos,234.0,27.9,72494,Cupertino,Tim Cook,United States
27,31,CVS Health,Varejo,139.0,9.9,208000,Woonsocket (Rhode Island),Larry Merlo,United States
31,35,Foxconn,Eletrônicos,133.0,6.6,1290000,Taiwan,Terry Gou,Taiwan
43,47,Costco,Varejo,114.0,7.1,189000,Issaquah,W. Craig Jelinek,United States
44,48,Hewlett Packard Enterprise,Eletrônicos,111.0,0.8,302000,Palo Alto,Meg Whitman,United States

In [30]:
print("\nSuperstore Sales by Year:")
display(df_superstore.groupby('year')['sales'].sum())

print("\nSuperstore Sales by Country:")
display(df_superstore.groupby('country')['sales'].sum().sort_values(ascending=False))

print("\nPotential Competitors Geographical Presence (Countries):")
display(df_competitors['País Final'].value_counts())

# Comparar países em comum
superstore_countries = df_superstore['country'].unique()
competitor_countries = df_competitors['País Final'].unique()

overlapping_countries = list(set(superstore_countries) & set(competitor_countries))

print(f"\nOverlapping Countries between Superstore and Potential Competitors: {overlapping_countries}")

Superstore Sales by Year:

year
2011    2259511
2012    2677493
2013    3405860
2014    4300041
Name: sales, dtype: int64

Superstore Sales by Country:

country
United States        2297354
Australia             925257
France                858930
China                 700591
Germany               628857
                      ...
Tajikistan               242
Macedonia                210
Eritrea                  188
Armenia                  156
Equatorial Guinea        150
Name: sales, Length: 147, dtype: int64

Potential Competitors Geographical Presence (Countries):

País Final
United States    5
China            1
Taiwan           1
Name: count, dtype: int64

Overlapping Countries between Superstore and Potential Competitors: ['China', 'United States', 'Taiwan']

In [31]:
overlapping_countries = ['China', 'Taiwan', 'United States']

df_superstore_integrated = df_superstore[df_superstore['country'].isin(overlapping_countries)].copy()
df_empresas_integrated = df_empresas[df_empresas['País Final'].isin(overlapping_countries)].copy()

print("Filtered df_superstore for overlapping countries:")
display(df_superstore_integrated.head())

print("\nFiltered df_empresas for overlapping countries:")
display(df_empresas_integrated.head())

Filtered df_superstore for overlapping countries:

,category,city,country,customer_ID,customer_name,discount,market,unknown,order_date,order_id,...,sales,segment,ship_date,ship_mode,shipping_cost,state,sub_category,year,market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07 0:00:00,CA-2011-130813,...,19,Consumer,2011-01-09 0:00:00,Second Class,4.37,California,Paper,2011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21 0:00:00,CA-2011-148614,...,19,Consumer,2011-01-26 0:00:00,Standard Class,0.94,California,Paper,2011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 0:00:00,CA-2011-118962,...,21,Consumer,2011-08-09 0:00:00,Standard Class,1.81,California,Paper,2011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 0:00:00,CA-2011-118962,...,111,Consumer,2011-08-09 0:00:00,Standard Class,4.59,California,Paper,2011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,2011-09-29 0:00:00,CA-2011-146969,...,6,Consumer,2011-10-03 0:00:00,Standard Class,1.32,California,Paper,2011,North America,40

Filtered df_empresas for overlapping countries:

,Classificação,Nome,Indústria,Receita (bilhões de USD),Crescimento da receita,Empregados,Sede,CEO,País Final
0,1,Walmart,Varejo,482.0,0.7,2300000,Bentonville (Arkansas),Doug McMillon,United States
1,2,State Grid,Eletrônicos,330.0,2.9,927839,Pequim,Shu Yinbiao,China
2,3,China National Petroleum,Petróleo e gás,299.0,30.2,1589508,Pequim,Wang Yilin,China
3,4,Sinopec,Petróleo e gás,294.0,34.1,810538,Pequim,Wang Yupu,China
5,6,Exxon Mobil,Petróleo e gás,246.0,35.6,75600,Irving (Texas),Rex Tillerson,United States

In [32]:
relevant_industries = ['Eletrônicos', 'Varejo']

df_relevant_competitors_integrated = df_empresas_integrated[
    df_empresas_integrated['Indústria'].isin(relevant_industries)
].copy()

print("Potential competitors in overlapping countries based on relevant industries:")
display(df_relevant_competitors_integrated)

Potential competitors in overlapping countries based on relevant industries:

,Classificação,Nome,Indústria,Receita (bilhões de USD),Crescimento da receita,Empregados,Sede,CEO,País Final
0,1,Walmart,Varejo,482.0,0.7,2300000,Bentonville (Arkansas),Doug McMillon,United States
1,2,State Grid,Eletrônicos,330.0,2.9,927839,Pequim,Shu Yinbiao,China
8,9,Apple,Eletrônicos,234.0,27.9,72494,Cupertino,Tim Cook,United States
27,31,CVS Health,Varejo,139.0,9.9,208000,Woonsocket (Rhode Island),Larry Merlo,United States
31,35,Foxconn,Eletrônicos,133.0,6.6,1290000,Taiwan,Terry Gou,Taiwan
43,47,Costco,Varejo,114.0,7.1,189000,Issaquah,W. Craig Jelinek,United States
44,48,Hewlett Packard Enterprise,Eletrônicos,111.0,0.8,302000,Palo Alto,Meg Whitman,United States

In [33]:
superstore_total_sales_overlapping_countries = df_superstore_integrated['sales'].sum()

print(f"Total Sales of Superstore in overlapping countries ('China', 'Taiwan', 'United States'): ${superstore_total_sales_overlapping_countries:,.2f}")

competitors_total_revenue_overlapping_countries = df_relevant_competitors_integrated[
    df_relevant_competitors_integrated['País Final'].isin(overlapping_countries)
]['Receita (bilhões de USD)'].sum() * 1_000_000_000

print(f"\nTotal Revenue of Relevant Competitors (headquartered in overlapping countries): ${competitors_total_revenue_overlapping_countries:,.2f}")

print("\nContextualizing the comparison:")
print("Superstore's sales are based on specific product lines and years.")
print("Competitors' revenue is global and covers várias indústrias.")
print("Portanto, a comparação é para dar uma noção geral, não uma comparação direta.")

Total Sales of Superstore in overlapping countries ('China', 'Taiwan', 'United States'): $3,005,593.00

Total Revenue of Relevant Competitors (headquartered in overlapping countries): $1,543,000,000,000.00

Contextualizing the comparison:
Superstore's sales are based on specific product lines and years.
Competitors' revenue is global and covers várias indústrias.
Portanto, a comparação é para dar uma noção geral, não uma comparação direta.